### ISSUE TITLE
Why is this a function?

### ISSUE THREAD

**Issue by olivia-may** [Krunegan/xp#10]
in `src/main.lua`
```
function xp.levelfunc(level)
	return (math.floor(1^level)+4999)
end
```
This function will always return `5000`. Why not just use a variable? Why does this function take `level` as an input when it will always return the same thing every time?

**Comment by Krunegan** [comment]
Originally, the XP required to level up was not a static value, but rather increased as the player leveled up. The function is still preserved even if it is not necessary.
